title: Resource Mod Loader
lang: en
description: the official documents of ResourceModLoader

remote_theme: egbendito/jekyll-theme-rtd

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock