title: Resource Mod Loader
lang: en
description: Official documentation for ResourceModLoader

remote_theme: Ecdcaeb/Archived-jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock