title: Resource Mod Loader
lang: en
description: the official documents of ResourceModLoader

remote_theme: ecdcaeb/dark-jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock